apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: tas-shared-infrastructure

resources:
  - namespace.yaml
  - config.yaml
  - redis.yaml
  - postgres.yaml
  - kafka.yaml
  - minio.yaml
  - keycloak.yaml
  - monitoring.yaml
  - grafana-dashboards-audimodal.yaml
  - pgadmin.yaml
  - alertmanager.yaml
  - dashboard.yaml
  - cert-manager.yaml
  - ingress-controller.yaml
  - ingress.yaml

commonLabels:
  project: tas
  tier: shared-infrastructure

namespace: tas-shared